language: node_js
node_js:
    - 11.14.0
cache: npm

install:
    - npm install

script:
    - npm build --prod

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: dist/portfolio